// The only module allowed to talk to the Rust shell. Every call is one Tauri command,
// and every command is either a query to display or an edit to hand to `sop-repo`, which
// decides whether it is allowed. Callers stay on the renderer side and never assume.

import { invoke } from "@tauri-apps/api/core";
import { open, save } from "@tauri-apps/plugin-dialog";
import type {
  CaptureInput,
  ChecklistEntry,
  Drift,
  ExportResult,
  Manifest,
  ProcedureChoice,
  ProjectView,
  PushResult,
  RunEventInput,
  RunMetaInput,
  RunView,
  SettingRow,
Status,
  StepInput,
  StepPatch,
  TestPlan,
} from "./types";

const text = (value: unknown): string =>
  value === null || value === undefined ? "" : String(value);

// ---- reading ----------------------------------------------------------------

export const manifest = (): Promise<Manifest> => invoke<string>("manifest_json").then(JSON.parse);

export const status = (): Promise<Status> => invoke<Status>("status");

export const validationReport = (): Promise<string> => invoke<string>("validation_report");

export const procedureChoices = (file: string | null): Promise<ProcedureChoice[]> =>
  invoke<ProcedureChoice[]>("procedure_choices", { file });

// ---- settings ---------------------------------------------------------------

export const settingsRows = (): Promise<SettingRow[]> => invoke<SettingRow[]>("settings_rows");

export const settingsPath = (): Promise<string> => invoke<string>("settings_path");

export const settingsRepoPath = (): Promise<string> => invoke<string>("settings_repo_path");

// ---- config (project + settings, one JSON document) -------------------------

export const configLoad = (): Promise<string> => invoke<string>("config_load");

export const configSave = (json: string): Promise<string> =>
  invoke<string>("config_save", { json });

export const settingsSet = (key: string, value: string): Promise<SettingRow[]> =>
  invoke<SettingRow[]>("settings_set", { key, value });

export const settingsUnset = (key: string): Promise<SettingRow[]> =>
  invoke<SettingRow[]>("settings_unset", { key });

export const openRepository = (path: string): Promise<Status> =>
  invoke<Status>("open_repository", { repo: path });

export const remoteUrl = (): Promise<string | null> => invoke<string | null>("remote_url");

export const remoteSet = (url: string): Promise<string> => invoke<string>("remote_set", { url });

// ---- project ----------------------------------------------------------------

export const projectFields = (): Promise<ProjectView> => invoke<ProjectView>("project_fields");

export const projectSet = (key: string, value: string): Promise<ProjectView> =>
  invoke<ProjectView>("project_set", { key, value });

// ---- editing ----------------------------------------------------------------

export const stepAdd = (file: string, step: StepInput, after: string | null): Promise<string> =>
  invoke<string>("step_add", { file, step, after });

export const stepUpdate = (file: string, id: string, patch: StepPatch): Promise<string> =>
  invoke<string>("step_update", { file, id, patch });

export const stepRemove = (file: string, id: string): Promise<string> =>
  invoke<string>("step_remove", { file, id });

export const itemMove = (file: string, kind: string, id: string, up: boolean): Promise<string> =>
  invoke<string>("item_move", { file, kind, id, up });

export const captureSet = (file: string, step: string, capture: CaptureInput): Promise<string> =>
  invoke<string>("capture_set", { file, step, capture });

export const captureRemove = (file: string, step: string, key: string): Promise<string> =>
  invoke<string>("capture_remove", { file, step, key });

export const includeAdd = (file: string, target: string): Promise<string> =>
  invoke<string>("include_add", { file, target });

export const includeRemove = (file: string, target: string): Promise<string> =>
  invoke<string>("include_remove", { file, target });

// ---- runs --------------------------------------------------------------------

export const runStart = (
  sop: string,
  runId: string,
  operator: string,
  site: string,
  overrideReason: string | null,
  meta: RunMetaInput
): Promise<RunView> =>
  invoke<RunView>("run_start", { sop, runId, operator, site, override: overrideReason, meta });

export const runRecord = (sop: string, runId: string, event: RunEventInput): Promise<RunView> =>
  invoke<RunView>("run_record", { sop, runId, event });

/// Render Markdown to HTML. The rules live in Rust (`sop_core::md`); this is the only
/// way the window asks for HTML.
export const renderMarkdown = (text: string): Promise<string> =>
  invoke<string>("render_markdown", { text });

export const runState = (sop: string, runId: string): Promise<RunView> =>
  invoke<RunView>("run_state", { sop, runId });

// Add a step to a running or ended run, after a named step or at the end. The id is
// generated by the shell (`adhoc-NNN`); this returns the run with the step merged in.
export const runAddStep = (
  sop: string,
  runId: string,
  title: string,
  after: string | null
): Promise<RunView> => invoke<RunView>("run_add_step", { sop, runId, title, after });

// Drop a tagged field marker: a label plus the tool's clock at this moment.
export const runMarker = (sop: string, runId: string, label: string): Promise<RunView> =>
  invoke<RunView>("run_marker", { sop, runId, label });

export const runDrift = (sop: string, runId: string): Promise<Drift> =>
  invoke<Drift>("run_drift", { sop, runId });

export const runEnd = (
  sop: string,
  runId: string,
  status: string,
  conclusion?: string | null,
  conclusionNote?: string | null
): Promise<RunView> =>
  invoke<RunView>("run_end", {
    sop,
    runId,
    status,
    conclusion: conclusion ?? null,
    conclusionNote: conclusionNote ?? null,
  });

export const runAttach = (sop: string, runId: string, step: string | null, path: string): Promise<RunView> =>
  invoke<RunView>("run_attach", { sop, runId, step, path });

// Remove one run (its record, run directory, and log directory). Returns how many paths
// were removed.
export const runDelete = (sop: string, runId: string): Promise<number> =>
  invoke<number>("run_delete", { sop, runId });

// Remove every run in the working copy. Returns how many runs there were.
export const runDeleteAll = (): Promise<number> => invoke<number>("run_delete_all");

// Pick any file to attach to a run (data, photo, etc.) via the native file picker.
export const pickDataFile = async (): Promise<string | null> => {
  const path = await open({ multiple: false });
  if (!path || Array.isArray(path)) return null;
  return path;
};

export const testPlans = (): Promise<TestPlan[]> => invoke<TestPlan[]>("test_plans");

// Pull the working copy (main) and the testcase repo (testcases), fast-forward only.
export const syncPull = (): Promise<string> => invoke<string>("sync_pull");

// Commit + push the testcase repo after a case/plan change.
export const testcasePush = (message: string): Promise<string> =>
  invoke<string>("testcase_push", { message });

export const duplicateTestCase = (path: string): Promise<string> =>
  invoke<string>("duplicate_test_case", { path });

export const deleteTestCase = (path: string): Promise<void> =>
  invoke<void>("delete_test_case", { path });

// Import any markdown file into a plan folder as a new test case.
export const importTestCase = (planPath: string, source: string): Promise<string> =>
  invoke<string>("import_test_case", { planPath, source });

// Create a new plan folder with a plan.md.
export const createTestPlan = (name: string, title: string): Promise<string> =>
  invoke<string>("create_test_plan", { name, title });

// ---- publishing ---------------------------------------------------------------

export const runExport = (sop: string, runId: string, out: string | null): Promise<ExportResult> =>
  invoke<ExportResult>("run_export", { sop, runId, out });

// Open the native save dialog (via tauri-plugin-dialog, which runs it on the correct
// thread) and hand the chosen path to the shell. Returns null when the operator cancels.
export const runExportDialog = async (sop: string, runId: string): Promise<ExportResult | null> => {
  const path = await save({
    defaultPath: `${sop}-${runId}.md`,
    filters: [{ name: "Markdown", extensions: ["md"] }],
  });
  if (!path) return null;
  return invoke<ExportResult>("run_export_to", { sop, runId, out: path });
};

// Export a summary table of every run, grouped by test plan and case, via the native
// save dialog.
export const runSummaryDialog = async (): Promise<string | null> => {
  const path = await save({
    defaultPath: "test-summary.md",
    filters: [{ name: "Markdown", extensions: ["md"] }],
  });
  if (!path) return null;
  return invoke<string>("run_summary", { out: path });
};

// ---- local file loading ------------------------------------------------------

// Parse a markdown file already chosen by the user (used to re-read an edited file).
export const loadExternalMd = (path: string): Promise<ChecklistEntry | null> =>
  invoke<string | null>("load_external_md", { path }).then((text) =>
    text ? JSON.parse(text) : null
  );

// Open the native file picker, then ask the shell to parse the chosen markdown file.
export const openExternalMdDialog = async (): Promise<ChecklistEntry | null> => {
  const path = await open({
    multiple: false,
    filters: [{ name: "Markdown", extensions: ["md", "markdown"] }],
  });
  if (!path || Array.isArray(path)) return null;
  const text = await invoke<string | null>("load_external_md", { path });
  return text ? JSON.parse(text) : null;
};

export const repoPush = (message: string): Promise<PushResult> =>
  invoke<PushResult>("repo_push", { message });

// ---- helpers ----------------------------------------------------------------

export { text };
